### ISSUE TITLE
exception while running lexvec

### ISSUE THREAD

**Issue by jave** [alexandres/lexvec#2]
I'm experimenting with building lexvec and running it.

+ go get github.com/alexandres/lexvec
+ go build

./lexvec -threads 64 -corpus 59m.txt -output lexvectors
.....
cds total: 67097075.384447

calculating ppmi matrix

create vectors

running lexvec
panic: nan

goroutine 102 [running]:
main.learn(0xc420210a20, 0xc447a48b40, 0xc424326d70, 0x5f7720, 0xc42132e570, 0xc424648000, 0x0, 0xc4a465a000, 0x12c, 0x12c, ...)
	/var/lib/jenkins/workspace/lexvec/lexvec.go:319 +0x4a0
main.main.func3(0xc4200ce330, 0xc4200ce370, 0xc4200ce310, 0xc4200ce2a0, 0xc6294e9980, 0xc449fb4200, 0x40, 0x40, 0xc449fb4000, 0x40, ...)
	/var/lib/jenkins/workspace/lexvec/lexvec.go:1022 +0x1929
created by main.main
	/var/lib/jenkins/workspace/lexvec/lexvec.go:1056 +0x2f22

**Comment by jave** [comment]
same thing happens with pre built binary

also note that this used to work 2016-08-10 with the same input file.

lexvec_v1.0.2_linux_amd64/lexvec -threads 64 -corpus 59m.txt -output lexvectors

build vocab
2370000
creating positional vocab words

vocab size: 103011
context vocab size: 412040
corpus size: 996025910
raw corpus size (only valid when constructing vocab): 1009822745

initializing cooc storage

identify coocurrence
1009822000
cds total: 67097075.384447

calculating ppmi matrix

create vectors

running lexvec
panic: nan

goroutine 107 [running]:
panic(0x571a60, 0xc8a30fbf50)
	/home/alex/go/src/runtime/panic.go:464 +0x3e6
main.learn(0xc82020db30, 0xc847f229f0, 0xc831a191d0, 0x7f7df5bff0b8, 0xc82604fb30, 0xc84c450000, 0x0, 0xc84c454000, 0x12c, 0x12c, ...)
	/home/alex/goworkspace/src/bitbucket.org/atsalle/lexvec_release2/lexvec.go:319 +0x6fd
main.main.func3(0xc8200c0660, 0xc8200c06f0, 0xc8200c05e8, 0xc8200c0520, 0xc870678e60, 0xc87b67c200, 0x40, 0x40, 0xc87b67c000, 0x40, ...)
	/home/alex/goworkspace/src/bitbucket.org/atsalle/lexvec_release2/lexvec.go:1035 +0x1e2c
created by main.main
	/home/alex/goworkspace/src/bitbucket.org/atsalle/lexvec_release2/lexvec.go:1056 +0x3d8b

**Comment by alexandres** [comment]
@jave :  So using https://github.com/alexandres/lexvec/releases/tag/v1.0.1 you don't get the nan?

**Comment by alexandres** [comment]
@jave : I just identified a bug that could be causing your issue. Can you clone master and build or download release 1.0.3 and let me know if it corrects your nan?

**Comment by jave** [comment]
The issue appears fixed now thanks!
