### ISSUE TITLE
Newer LexVec

### ISSUE THREAD

**Issue by DonaldTsang** [alexandres/lexvec#3]
Requesting an updated version of LexVec with Common Crawl 2017,  
with 3 million most frequent words to be competitive with GloVe.  
Bonus: Common Crawl 2015~2017 to get 100B tokens (like word2vec)

**Comment by DonaldTsang** [comment]
Where I find LexVec, GloVe and Word2Vec:  
https://github.com/Hironsan/awesome-embedding-models#datasets

**Comment by DonaldTsang** [comment]
@alexandres how does LexVec compete with Fasttext with OOV words?

**Comment by alexandres** [comment]
Have a look at http://www.aclweb.org/anthology/W18-1209 which compares performance on the Rare Words dataset and performs some qualitative analysis on OOV words.
