### ISSUE TITLE
convert to .bin format

### ISSUE THREAD

**Issue by fkolokathi** [alexandres/lexvec#6]
Hello! Is there a way to convert all the files of embeddings in bin format?

**Comment by alexandres** [comment]
Hi! 

Yes, it is possible. LexVec's text format is the same as word2vec's. Have a look at https://github.com/marekrei/convertvec . It can convert text->bin and bin->text.

LexVec also has binary models for the subword models. You can load this model using https://github.com/alexandres/lexvec/blob/master/python/lexvec/model.py .

Hope that helps!
