### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by iris-qq** [alexandres/lexvec#7]
when i install this package,i used make,one error occurred.pls help
```
CC="clang" CGO_CFLAGS="-Ofast -std=gnu99 -march=native" go build --ldflags '-extldflags "-static"' -o lexvec
# github.com/alexandres/lexvec
/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [optimal] Error 2

```

**Comment by alexandres** [comment]
On macOS you'd need to do some work to get static linking to work (see https://stackoverflow.com/questions/16718406/statically-linked-libraries-on-mac).

As an easier fix, change the LexVec Makefile:

```
-BUILD = go build --ldflags '-extldflags "-static"' -o $(OBJ)
+BUILD = go build -o $(OBJ)
```

Tested on macOS 10.14.2 and it works!

**Comment by alexandres** [comment]
This issue doesn't seem to appear as of 10.15.4 so I'm closing it!
